### ISSUE TITLE
[Priority 1] Half-space insertion with chained conditions

### ISSUE THREAD

**Issue by dgventura** [Cascable/localisation-issues#1]
When you have two conditions together, a half-width space appears to be inserted before and after the word "or"; e.g. "it's evening golden hour or during sunset".  In Japanese there are never any spaces between words, so in this UI a space should not be included in the the formatting itself, but rather in all the translated values for keys of the `SeparatorSentenceFragment` types.  In English this could be ` or ` where Japanese stays `または`

**Comment by dgventura** [comment]
![IMG_0146](https://github.com/Cascable/localisation-issues/assets/1404389/d098bd5e-2f3b-44a9-8afb-60093c75bdd9)

**Comment by iKenndac** [comment]
Added `ListInSentenceItemSeparatorIncludingWordSpacing = ", "` and `ListInSentenceFinalItemSeparatorIncludingWordSpacing = " or "`
