### ISSUE TITLE
[Priority 1] Units are not translated, and units never used in Japan are present

### ISSUE THREAD

**Issue by dgventura** [Cascable/localisation-issues#2]
In the preferences panel you can choose units: inches, feet, etc.  However, F*, mph, inches and feet are never used in Japan so they should not appear at all if the locale/language is Japan.  Also, though `mm` and `cm` are fine, `メートル` should be used for `meters` , `海里` for `knots`. Any that are not letter abbreviations should be translated.
![units](https://github.com/Cascable/localisation-issues/assets/1404389/63a9393e-34b3-464b-bb07-467f763f90e2)

**Comment by iKenndac** [comment]
Added keys for the various units. I hear you on the defaults, but all the units need to remain and be translated to allow sharing of scenes between users. That defaults menu we can think about though.
