### ISSUE TITLE
[Priority 1] Pop-out menu showing "New scene from template" causes line wraps

### ISSUE THREAD

**Issue by dgventura** [Cascable/localisation-issues#3]
The "new scene" button appears to have a fixed width popover that causes line breaks.  We cannot shorten these any more and they look bad in a frequently used button with line breaks in the middle of words.  We recommend making the box wider or applying a font "resize to fit" constraint on the labels.

![templateNames](https://github.com/Cascable/localisation-issues/assets/1404389/c29a4847-2e0d-471c-abee-cd2781bba4a1)

**Comment by dgventura** [comment]
![426715918_2367041643484742_4204153525253467289_n](https://github.com/Cascable/localisation-issues/assets/1404389/8dbcdd03-3bab-41b1-8832-0823b81c7c35)

**Comment by iKenndac** [comment]
SwiftUI doesn't let us manually change the size of menus or affect the labels within. We'll need to rebuild this component entirely.

**Comment by iKenndac** [comment]
Fixed with a custom component. 

![RocketSim_Screenshot_iPhone_15_Pro_6 1_2024-02-14_5 21 56 PM](https://github.com/Cascable/localisation-issues/assets/514900/d09f34ac-5407-491e-916d-9923912be30e)
