### ISSUE TITLE
[Priority 2] Time range should have an "until" word after it.

### ISSUE THREAD

**Issue by dgventura** [Cascable/localisation-issues#4]
When setting a time range for a condition, e.g. "9:00 to 17:00", the "to" is translated, but in Japanese, it is correct to say "from 9:00 to 17:00".  However, the way the grammar reads is literally "9:00 from 17:00 until".  So we need to write a word after the second time.

We recommend putting a "timeRangeEndingWord" or similar key that would be blank in English, and `まで` in Japanese, so we can render it properly as `9:00から17:00まで`
![timeRange](https://github.com/Cascable/localisation-issues/assets/1404389/60bc1a1c-db09-457e-9c25-69d5eb70a45c)

**Comment by iKenndac** [comment]
Added `TimeRangeEditorTimeIsSuffix`
