### ISSUE TITLE
[Priority 3] ScenesListNextUpcomingTitle line wrap

### ISSUE THREAD

**Issue by dgventura** [Cascable/localisation-issues#5]
`ScenesListNextUpcomingTitle` in Japanese linewraps.  We need to keep the value as is to match other terminology in the app.

We recommend applying an autoresize to fit constraint on the title text to prevent a line wrap from happening on phones.
![nextShutterChance](https://github.com/Cascable/localisation-issues/assets/1404389/ccf95355-1c67-4854-b9c3-fb7ed92d801c)

**Comment by iKenndac** [comment]
Fixed by shrinking the title down on narrower widths
