### ISSUE TITLE
[Priority 2] Order of value conditions is grammatically incorrect.

### ISSUE THREAD

**Issue by dgventura** [Cascable/localisation-issues#7]
For the conditions that have 3 sections of the format `attribute` `equal to/less/greater than` `value`, the order is incorrect in Japanese.  In Japanese they should be laid out `attribute` `value` `equal to/less/greater than`.  We recommend using a meta formatting string like we have in `notification.opportunity.completed` and we have the ability to change the order of the values, and then you lay out the controls top to bottom based on that.

In the current example, it feels like it's reading as as "cloud cover 50% less than", if you could imagine controls being laid out in 3 sections like that.

![threeParamsOrder](https://github.com/Cascable/localisation-issues/assets/1404389/c4121c49-0071-4447-a757-2dd9450be526)

**Comment by iKenndac** [comment]
This particular screen now reverses the middle and last sections when run in Japanese.
