### ISSUE TITLE
[Priority 1] Article description title seems to use "ellipses" instead of line wrap or auto-shrink to fit

### ISSUE THREAD

**Issue by dgventura** [Cascable/localisation-issues#8]
In the article for sunlight/moonlight vibrancy, the article header goes to ellipses in Japanese.  It should auto-shrink to fit or failing that at least line wrap.  If this layout is reused for all articles it's probably a general issue and we haven't noticed any other instances yet.

![IMG_2E7791747735-1](https://github.com/Cascable/localisation-issues/assets/1404389/3198d348-9958-4a59-80ab-d9bbcca38c92)

**Comment by iKenndac** [comment]
Fixed (hopefully) by using inline navigation titles.
