### ISSUE TITLE
[Priority 4] Nighttime scenes can have daytime looking thumbnails

### ISSUE THREAD

**Issue by dgventura** [Cascable/localisation-issues#9]
![IMG_925D64EB8872-1](https://github.com/Cascable/localisation-issues/assets/1404389/675c4662-3959-43a5-bce7-080c8b8a3122)

In creating a scene that takes place explicitly between 19:00 and 03:00 (or any slice of night AFAICT) the thumbnail is not the moon/night one, but daylight.  Shows up in the widget and the app itself as sunny.

**Comment by iKenndac** [comment]
Fixed by not being terrible at maths.
